language: java
matrix:
  include:
    - os: osx
      osx_image: xcode7.2
    - os: linux
      jdk:
        - oraclejdk8
        - oraclejdk7

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
