language: java
matrix:
  include:
    - os: osx
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
